# Generated by Django 5.1.1 on 2024-12-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='snacks',
            name='quantity',
            field=models.IntegerField(default=20),
        ),
    ]
