# Generated by Django 5.1.1 on 2024-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_snacks_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='snacks',
            name='category',
            field=models.CharField(default='Indian', max_length=200),
        ),
    ]
