# Generated by Django 5.1.1 on 2024-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_snacks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_image',
            field=models.ImageField(default='null', upload_to='orders'),
        ),
    ]
