# Generated by Django 5.1.1 on 2024-12-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_order_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='Indian', max_length=200),
        ),
    ]
