# Generated by Django 5.1.1 on 2024-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_booktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='members',
            field=models.IntegerField(default=1),
        ),
    ]
