# Generated by Django 5.1.1 on 2024-12-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_booktable_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTable',
        ),
    ]
